/**
 * Discrete logarithm extraction by Shor's two-register algorithm.
 *
 * Run:  node examples/node/dlog-shor.js
 *       DLOG_P=17 DLOG_G=3 DLOG_X=5 node examples/node/dlog-shor.js
 *
 * Given a cyclic group generated by g of known order r, and an element h = g^x,
 * the exponent x is recovered by preparing
 *
 *     |a> |b> |1>  ->  |a> |b> |g^a h^b>
 *
 * over two exponent registers in uniform superposition, then applying an inverse
 * quantum Fourier transform to each. Collapsing the group register onto a coset
 * leaves sum_b |k - x b> |b>, whose transform is supported entirely on pairs
 * satisfying beta = x alpha (mod r). The exponent follows as x = beta alpha^-1
 * whenever alpha is invertible.
 *
 * g is required to have order a power of two, so that 2^t = r exactly. The
 * transform is then exact, every measured pair satisfies the relation without
 * error, and no continued-fraction post-processing or peak selection is needed.
 *
 * This constrains g, not p. Any group of order (p-1) = 2^k * m contains an
 * element of order 2^k, so a suitable generator exists for every prime; if the
 * supplied g is unsuitable the script computes one and reports it rather than
 * simply refusing. Handling arbitrary r would require approximating the
 * transform and post-processing the peaks, which is deliberately out of scope.
 *
 * Controlled modular multiplication uses the Beauregard construction and is
 * simulated exactly. The same problem over an elliptic curve group underlies
 * ECDSA; secp256k1 has a 256-bit group order, for which published resource
 * estimates are on the order of 10^3 logical qubits.
 */
import { Circuit, modPow, modInverse, beauregardU, applyIqft, DEVICES } from '../../dist/ket.js'

const P = BigInt(process.env.DLOG_P ?? 17)
const G = BigInt(process.env.DLOG_G ?? 3)
const X = BigInt(process.env.DLOG_X ?? 5)
const SHOTS = Number(process.env.DLOG_SHOTS ?? 200)
// Each noisy shot is an independent trajectory through the whole circuit, which
// costs minutes. The analytic estimate below is exact and instant, so sampling
// is opt-in and only confirms it.
const NOISY_SHOTS = Number(process.env.DLOG_NOISY_SHOTS ?? 0)
const NOISE_DEVICE = process.env.DLOG_NOISE ?? 'forte-1'

const assert = (cond, reason) => {
  if (!cond) { console.error(`\nassertion failed: ${reason}`); process.exit(1) }
}

console.log("Discrete logarithm extraction by Shor's two-register algorithm")
console.log('==============================================================')

// ── 1. Instance ───────────────────────────────────────────────────────────────
// The order of g is obtained by enumeration; the algorithm assumes it known.
let r = 0n
for (let k = 1n; k < P; k++) if (modPow(G, k, P) === 1n) { r = k; break }
assert(r > 0n, `g=${G} has no finite order modulo ${P}`)

if ((r & (r - 1n)) !== 0n) {
  // Every group of order 2^k * m has an element of order 2^k: raise a primitive
  // root to the power m. Report it instead of leaving the caller to derive one.
  let twoPart = 1n, m = P - 1n
  while (m % 2n === 0n) { m /= 2n; twoPart *= 2n }
  let suggestion
  for (let cand = 2n; cand < P && suggestion === undefined; cand++) {
    let ord = 0n
    for (let k = 1n; k < P; k++) if (modPow(cand, k, P) === 1n) { ord = k; break }
    if (ord === twoPart) suggestion = cand
  }
  console.error(`\ng=${G} has order ${r}, which is not a power of two, so the transform`)
  console.error(`would not be exact. The largest power of two dividing p-1=${P - 1n} is ${twoPart}.`)
  console.error(suggestion !== undefined
    ? `Use DLOG_G=${suggestion}, which has order ${twoPart}, with x < ${twoPart}.`
    : `No element of order ${twoPart} was found modulo ${P}; choose another prime.`)
  process.exit(1)
}
assert(X < r, `exponent x=${X} must be less than r=${r}`)

const h = modPow(G, X, P)
const t = r.toString(2).length - 1        // 2^t = r
const n = P.toString(2).length            // bits required to hold a group element

console.log('\n1. Instance')
console.log(`   p = ${P}, g = ${G}, order r = ${r} = 2^${t}`)
console.log(`   x = ${X} (withheld), h = g^x mod p = ${h}`)
console.log('   supplied to the procedure: (p, g, r, h)')

// ── 2. Register layout ────────────────────────────────────────────────────────
const A = 0, B = A + t, XR = B + t, ACC = XR + n, ANC = ACC + n + 1
const total = ANC + 1
console.log('\n2. Register layout')
console.log(`   A[${t}] exponent of g, B[${t}] exponent of h, X[${n}] group element,`)
console.log(`   accumulator[${n + 1}], ancilla[1]; ${total} qubits total`)

// ── 3. Circuit ────────────────────────────────────────────────────────────────
let c = new Circuit(total)
for (let j = 0; j < t; j++) c = c.h(A + j).h(B + j)
c = c.x(XR)                                // |X> = |1>, the group identity

for (const [base, reg] of [[G, A], [h, B]]) {
  for (let j = 0; j < t; j++) {
    const a = modPow(base, 1n << BigInt(j), P)
    c = beauregardU(c, n, a, modInverse(a, P), P, reg + j, XR, ACC, ANC)
  }
}

c = applyIqft(c, t, A)
c = applyIqft(c, t, B)

console.log('\n3. Circuit')
console.log(`   ${2 * t} controlled modular multiplications, 2 inverse QFTs, depth ${c.depth()}`)

// ── 4. Measurement ────────────────────────────────────────────────────────────
const t0 = performance.now()
const dist = c.run({ shots: SHOTS, seed: 3 })
const secs = (performance.now() - t0) / 1000
console.log('\n4. Measurement')
console.log(`   ${SHOTS} shots, wall time ${secs.toFixed(1)} s`)

const read = (bits, off) => {
  let v = 0n
  for (let j = 0; j < t; j++) if (bits[off + j] === '1') v |= 1n << BigInt(j)
  return v
}

// The support condition is exact for r = 2^t, so it is measured, not assumed.
let offSupport = 0
for (const [bits, prob] of Object.entries(dist.probs)) {
  const alpha = read(bits, A), beta = read(bits, B)
  if (((beta - X * alpha) % r + r) % r !== 0n) offSupport += prob
}
console.log(`   outcomes violating beta = x alpha (mod r): ${(offSupport * 100).toFixed(2)} %`)
assert(offSupport < 1e-9, `${(offSupport * 100).toFixed(2)}% of amplitude lies off the predicted support`)

// ── 5. Exponent recovery ──────────────────────────────────────────────────────
const votes = new Map()
let usable = 0
for (const [bits, prob] of Object.entries(dist.probs)) {
  const alpha = read(bits, A), beta = read(bits, B)
  if (alpha % 2n === 0n) continue           // alpha not invertible modulo 2^t
  const x = (beta * modInverse(alpha, r)) % r
  usable += prob
  votes.set(x, (votes.get(x) ?? 0) + prob)
}
const ranked = [...votes].sort((u, v) => v[1] - u[1])
assert(ranked.length > 0, 'no outcome had an invertible alpha')

console.log('\n5. Exponent recovery')
console.log(`   usable outcomes (alpha odd): ${(usable * 100).toFixed(1)} %`)
console.log('   candidate   weight    g^x mod p   consistent')
for (const [x, w] of ranked.slice(0, 5)) {
  const gx = modPow(G, x, P)
  console.log(`   x = ${String(x).padStart(3)}  ${(w * 100).toFixed(1).padStart(6)} %  ${String(gx).padStart(9)}   ${gx === h ? 'yes' : 'no'}`)
}

// ── 6. Verification ───────────────────────────────────────────────────────────
const [best] = ranked
assert(modPow(G, best[0], P) === h, `recovered x=${best[0]} does not satisfy g^x = h`)
assert(best[0] === X, `recovered x=${best[0]} differs from the withheld value ${X}`)

console.log('\n6. Verification')
console.log(`   g^${best[0]} mod ${P} = ${modPow(G, best[0], P)} = h`)
console.log('   recovered exponent agrees with the withheld value')

console.log('\nResult')
console.log(`   x = ${best[0]} recovered from (p, g, r, h) using ${total} qubits in ${secs.toFixed(1)} s.`)
console.log(`   ${(ranked[0][1] * 100).toFixed(0)} % of usable outcomes agreed. All checks passed.`)

// ── 7. Hardware feasibility ───────────────────────────────────────────────────
// The preceding sections assume noiseless evolution. This section quantifies
// what the same circuit would do on hardware, which is the difference between
// "the algorithm is correct" and "a device can run it".
const { oneQubit: oneQ, twoQubit: twoQ } = c.gateCounts()

console.log('\n7. Hardware feasibility')
console.log(`   gate counts: ${oneQ} single-qubit, ${twoQ} two-qubit-equivalent`)
// IonQ systems currently accepting jobs. Per-gate error is what decides this,
// so the figures below stand in for any trapped-ion device of this generation.
console.log('   device                p1          p2          P(error-free run)')
for (const [name, dv] of Object.entries(DEVICES)) {
  if (dv.vendor !== 'IonQ' || dv.status !== 'available') continue
  const pOk = (1 - dv.noise.p1) ** oneQ * (1 - dv.noise.p2) ** twoQ
  console.log(`   ${name.padEnd(20)}  ${dv.noise.p1.toExponential(1).padEnd(10)}  ${dv.noise.p2.toExponential(1).padEnd(10)}  ${pOk.toExponential(2)}`)
}
console.log(`   the circuit uses ${total} qubits; several available devices exceed that.`)
console.log('   the binding constraint is gate count against per-gate error, not width.')
if (NOISY_SHOTS === 0) {
  console.log(`   set DLOG_NOISY_SHOTS=16 to confirm this empirically (minutes).`)
}

if (NOISY_SHOTS > 0) {
  const uniform = 100 / Number(r)
  const t1 = performance.now()
  const noisy = c.run({ shots: NOISY_SHOTS, seed: 5, noise: NOISE_DEVICE })
  let onSupport = 0
  for (const [bits, prob] of Object.entries(noisy.probs)) {
    const alpha = read(bits, A), beta = read(bits, B)
    if (((beta - X * alpha) % r + r) % r === 0n) onSupport += prob
  }
  console.log(`\n   empirical, ${NOISY_SHOTS} shots under ${NOISE_DEVICE} depolarizing noise ` +
              `(${((performance.now() - t1) / 1000).toFixed(0)} s):`)
  console.log(`     outcomes on the predicted support: ${(onSupport * 100).toFixed(1)} %`)
  console.log(`     noiseless: 100.0 %    uniform guessing: ${uniform.toFixed(1)} %`)
  console.log(`   ${onSupport * 100 <= uniform * 2 ? 'the signal is not distinguishable from guessing.'
                                                   : 'residual signal survives at this sample size.'}`)
}
