export { Circuit, Distribution } from './circuit.js'
export { qft, iqft, grover, groverAncilla, phaseEstimation, vqe, gradient, minimize, gradientMps, minimizeMps, trotter, qaoa, maxCutHamiltonian, realAmplitudes, efficientSU2, PauliOp } from './algorithms.js'
export type { PauliTerm, MinimizeOptions, MinimizeResult, MinimizeMpsOptions, AnsatzFn } from './algorithms.js'
export type { DenseOptions } from './dense.js'
export type { RunOptions, NoiseParams, MpsRunOptions, SimulateOptions, StabilizerRankRunOptions, GateCounts, IonQGate, IonQCircuit, IonQDeviceInfo, DeviceInfo, CircuitJSON, FlatOp, SvgTheme } from './circuit.js'
export { IONQ_DEVICES, DEVICES } from './circuit.js'
export { factor, shorBeauregard, shorCircuit, modPow, modInverse, gcd, continuedFractions, phiAdd, applyQft, applyIqft, beauregardU, cMultModAdd, phiAddMod, ccPhiAddMod } from './beauregard.js'
export type { ShorResult } from './beauregard.js'
export { CliffordSim } from './clifford.js'
export { submitIonQ, getIonQJob, awaitIonQJob, cancelIonQJob, getIonQResults, runIonQ, ionqSubmitRequest, ionqHistogramToCounts, countsToProbs } from './ionq.js'
export type { IonQJob, IonQJobStatus, IonQOptions, IonQSubmitOptions, IonQPollOptions, RunIonQOptions } from './ionq.js'
export { StabilizerCH, randomEquatorial } from './stabilizer-ch.js'
export { StabilizerRank, extent, termBudget } from './stabilizer-rank.js'
export type { StabilizerRankOptions, NormEstimateOptions } from './stabilizer-rank.js'
export type { SampleOptions } from './stabilizer-sampling.js'
export { maxTGates, bytesPerTerm } from './stabilizer-capacity.js'
export type { MaxTGatesOptions } from './stabilizer-capacity.js'
export { amplitudeByContraction, amplitudeBatchByContraction, sampleByContraction, amplitudeBySlicedContraction, planContraction, planContractionPartitioned, planBest, evaluatePlan, sliceContraction, contractSliced, projectTensor, permuteTensor, circuitNetwork, contractNetwork, contractPair } from './tensor-network.js'
export type { Tensor, ContractionPlan, ContractionStep, AmplitudeResult, SlicedPlan, AmplitudeBatch, ContractionSample } from './tensor-network.js'
export { pauliPathExpectation } from './pauli-path.js'
export type { PauliPathResult, PauliPathOptions, PauliLetter } from './pauli-path.js'
export { DensityMatrix } from './density.js'
export type { DmNoiseParams } from './density.js'
export { c, ZERO, ONE, I, add, mul, scale, conj, norm2 } from './complex.js'
export type { Complex } from './complex.js'
export { Id, H, X, Y, Z, S, Si, T, Ti, V, Vi, Rx, Ry, Rz, R2, R4, R8, U1, U2, U3,
         Xx, Yy, Zz, Xy, ISwap, SrSwap, Gpi, Gpi2, Ms } from './gates.js'
export type { Gate2x2, Gate4x4, StateVector } from './statevector.js'
// Re-exported so `@kirkelliott/ket/compat` can be a thin alias of this bundle
// rather than a second copy of the engine — two copies would make a Circuit from
// one unusable by the other.
export { QuantumCircuit } from './compat.js'
export type { CompatCondition, CompatGateOptions, CompatRunOptions, CompatSavedCircuit, CompatSavedGate } from './compat.js'
